server:
  port: 9091
  jackson:
    data-formate: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love?serUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2b8
    username: root
    password: root

  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间(毫秒)
    timeout: 36000ms
    # Redis默认情况下有16个分片，默认0
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描mybatis
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
